[package]
name = "scopeguard"
version = "0.1.0"

license = "MIT/Apache-2.0"
repository = "https://github.com/bluss/scopeguard"
authors = ["bluss"]

description = "A convenient RAII scope guard."

keywords = ["scope-guard", "defer"]

